Updated the upgrade script

diff --git a/upgrade/ISD-DB-Migrate-job.yaml b/upgrade/ISD-DB-Migrate-job.yaml
--- a/upgrade/ISD-DB-Migrate-job.yaml
+++ b/upgrade/ISD-DB-Migrate-job.yaml
@@ -31,25 +31,52 @@ spec:
               elif [ "$source" == "3.11" ]; then
 
                            echo "upgrading  v3.11 to v3.12"
-                 
+
                              echo "started migration"
-                  
+
                            python3 migration_v3.11.x_to_v3.12.py platformdb $host oesdb $host  opsmx $host auditdb $host visibilitydb $host $port  $oesgateurl http://sapor-gate:8084 $oesuiurl $user $saporpassword $pguser $pgpassword
-                
-                
+
               elif [ "$source" == "3.12" ]; then
-              echo "upgrading  v3.12 to v4.0"
+
+                           echo "upgrading  v3.12 to v4.0"
+
+                             echo "started migration"
+
+                           #echo "python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb oes-db visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 "$release"-redis-master 6379 $redispassword"
+
+                           python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb oes-db visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 "$release"-redis-master 6379 $redispassword
 
               else
-                 
+
                  echo "Some went wrong in mapping Migration script"
-                  
+
               fi
+                      CREATION_TIME=`date -u +"%d-%m-%Y"`
+                       
+                        
+                      mkdir -p /tmp/$CREATION_TIME/
+                      echo $CREATION_TIME
+                      
+                      
+                            ls -ltra /tmp/*.log
+                      
+                            tar -czvf /tmp/OpsMx-Logs.tar.gz /tmp/*.log
+
+                           curl --location --request PUT 'https://opsmx.jfrog.io/artifactory/opsmx-logs/internal/OpsMx-Logs.tar.gz' --header 'Authorization: Basic YW5vb3B0ZWo6T3BzTXhAMTIz' --header 'Content-Type: application/gzip' --data-binary '@/tmp/OpsMx-Logs.tar.gz'
+
+                        if [ $? -eq 0 ]; then
+
+                                          echo "Logs sucessfully pushed to https://opsmx.jfrog.io/artifactory/opsmx-logs/internal/OpsMx-Logs.tar.gz"
+                              else
+                                     echo "Failed to push logs to https://opsmx.jfrog.io/artifactory/opsmx-logs/internal/OpsMx-Logs.tar.gz"
+
+                                     exit 1
+                          fi
           command:
             - /bin/bash
             - +x
             - '-c'
-          image: 'quay.io/opsmxpublic/ubi8-oes-platform:v3.12.5'
+          image: 'quay.io/vulnscanning/temp/oes-platform:v4.0.1-rc1'
           name: exec-db-upgrade
           envFrom:
             - configMapRef:
@@ -70,7 +97,7 @@ spec:
             - /bin/bash
             - +x
             - '-c'
-          image: 'quay.io/opsmxpublic/opsmx-custom-binaries:upgrade-scripts'
+          image: 'quay.io/opsmxpublic/opsmx-custom-binaries:opsmx-isd-scripts4'
           name: get-script
           envFrom:
             - configMapRef:
@@ -83,4 +110,3 @@ spec:
       volumes:
         - emptyDir: {}
           name: repo-volume
-
